# Generated by Django 3.0.5 on 2020-04-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField()),
                ('call_strike', models.FloatField(default=0)),
                ('call_premium', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Put',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put_date', models.DateField()),
                ('put_strike', models.FloatField(default=0)),
                ('put_premium', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
